# ============================================================
# Ocean-Atmosphere Coupled Shallow Water Equations
# Ocean : Equatorial beta-plane, Arakawa C-grid, RK4
# Atmosphere: Long-wave SWE, full prognostic (U_a, V_a, φ_a)
# ============================================================
#
# Ocean (linearized beta-plane SWE):
#   ∂u/∂t =  β·y·v̄  - g'·∂h/∂x - r·u  -  wind_coeff·(U_a + U_bg)
#   ∂v/∂t = -β·y·ū  - g'·∂h/∂y - r·v
#   ∂h/∂t = -H·(∂u/∂x + ∂v/∂y)
#
# Atmosphere — anomaly model, damped toward zero:
#   ∂U_a/∂t =  β·y·V̄_a - ∂φ_a/∂x - ε_a·U_a
#   ∂V_a/∂t = -β·y·Ū_a - ∂φ_a/∂y - ε_a·V_a
#   ∂φ_a/∂t = +α·h - c_a²·(∂U_a/∂x + ∂V_a/∂y)
#
# Mean-state separation (Zebiak-Cane linearisation):
#   U_bg = prescribed background Walker wind (Gaussian in y, fixed in time).
#   The ocean feels wind_coeff·(U_a + U_bg):
#     - U_bg drives a steady thermocline tilt (deep west / shallow east)
#       so that west and east thermocline curves never cross.
#       Δh_bg = wind_coeff·U_trade·Lx/g'  [computed at startup].
#     - U_a is the ENSO anomaly generated by Bjerknes coupling.
#   The atmosphere is initialised at U_a=0 (no anomaly) and damped toward

#
# Sign conventions (first baroclinic mode):
#   φ_a describes the UPPER troposphere.  Warm SST (h>0) drives
#   convection → warm column → HIGH upper-level pressure → +α·h ✓
#
#   u_surface = −U_a  (baroclinic mode: surface and upper-level winds
#   have opposite signs).
#   τ = −wind_coeff·(U_a+U_bg) → ocean wind stress.
#   With U_a+U_bg > 0 (upper westerlies), surface wind is westward
#   → ocean driven westward → correct Bjerknes feedback.
#
# Initial conditions:
#   Ocean : h = -h_amp·(x/(Lx/2))·exp(-y²/4L_d²),  u=v=0
#   Atm   : U_a=0,  V_a=0,  φ_a=0  (anomaly model, start at rest state)
#
# Grid (same Arakawa C-grid for ocean and atmosphere):
#   h,φ_a at cell centres;  u,U_a at east faces;  v,V_a at north faces
#
# Boundaries — x: solid walls (u=U_a=0 at west & east)
#            — y: Neumann + quadratic sponge (north & south)
# Temporal: simultaneous RK4 for all 6 prognostic fields
# ============================================================

using Printf
using Statistics
using JLD2

include("visualize.jl")

# ============================================================
# Atmosphere kernel: RHS for (U_a, V_a, φ_a)
# Anomaly model: U_a damped toward zero (not toward U_bg).
# No geostrophic-adjustment instability.
# ============================================================
@parallel_indices (ix, iy) function compute_atm_rhs!(
        dU_a, dV_a, dφ_a,
        U_a,  V_a,  φ_a,  h,
        Y_h, Y_v,
        Rs_h, Rs_v,
        β, ε_a, c_a_sq, α_atm,
        dx, dy, Nx, Ny)

    if 1 ≤ ix ≤ Nx && 1 ≤ iy ≤ Ny

        invdx = 1.0 / dx
        invdy = 1.0 / dy

        # dφ_a at h-point (ix, iy)
        U_a_west  = (ix == 1) ? 0.0         : U_a[ix-1, iy]
        V_a_south = (iy == 1) ? V_a[ix, iy] : V_a[ix, iy-1]

        dφ_a[ix, iy] = α_atm * h[ix, iy] -
                       c_a_sq * ((U_a[ix, iy] - U_a_west ) * invdx +
                                 (V_a[ix, iy] - V_a_south) * invdy) -
                       Rs_h[ix, iy] * φ_a[ix, iy]

        # dU_a at u-point (ix+½, iy) — damped toward zero
        if ix < Nx
            dφ_dx = (φ_a[ix+1, iy] - φ_a[ix, iy]) * invdx

            v_nw = V_a[ix,   iy];  v_ne = V_a[ix+1, iy]
            v_sw = (iy == 1) ? V_a[ix,   iy] : V_a[ix,   iy-1]
            v_se = (iy == 1) ? V_a[ix+1, iy] : V_a[ix+1, iy-1]
            V_avg = 0.25 * (v_nw + v_ne + v_sw + v_se)

            dU_a[ix, iy] = β * Y_h[ix, iy] * V_avg - dφ_dx -
                           (ε_a + Rs_h[ix, iy]) * U_a[ix, iy]
        else
            dU_a[ix, iy] = 0.0
        end

        # dV_a at v-point (ix, iy+½)
        U_a_se = U_a[ix,   iy]
        U_a_sw = (ix == 1) ? 0.0 : U_a[ix-1, iy]

        if iy < Ny
            dφ_dy = (φ_a[ix, iy+1] - φ_a[ix, iy]) * invdy
            U_a_ne = U_a[ix,   iy+1]
            U_a_nw = (ix == 1) ? 0.0 : U_a[ix-1, iy+1]
        else
            dφ_dy = 0.0
            U_a_ne = U_a_se
            U_a_nw = U_a_sw
        end
        U_avg = 0.25 * (U_a_se + U_a_sw + U_a_ne + U_a_nw)

        dV_a[ix, iy] = -β * Y_v[ix, iy] * U_avg - dφ_dy -
                       (ε_a + Rs_v[ix, iy]) * V_a[ix, iy]
    end
    return
end

# ============================================================
# Ocean kernel: RHS for (u, v, h)
# Wind stress = wind_coeff · (U_a + U_bg):
#   U_bg — fixed background trade wind → mean thermocline tilt
#   U_a  — ENSO anomaly from Bjerknes coupling
# ============================================================
@parallel_indices (ix, iy) function compute_rhs!(
        du, dv, dh,
        u,  v,  h,
        U_a, U_bg,
        Y_h, Y_v,
        Rs_h, Rs_v,
        β, g_p, r, H,
        wind_coeff,
        dx, dy, Nx, Ny)

    if 1 ≤ ix ≤ Nx && 1 ≤ iy ≤ Ny

        invdx = 1.0 / dx
        invdy = 1.0 / dy

        # dh at h-point (ix, iy)
        u_west  = (ix == 1) ? 0.0       : u[ix-1, iy]
        v_south = (iy == 1) ? v[ix, iy] : v[ix, iy-1]

        dh[ix, iy] = -H  * ((u[ix, iy] - u_west ) * invdx +
                             (v[ix, iy] - v_south) * invdy) -
                     Rs_h[ix, iy] * h[ix, iy]

        # du at u-point (ix+½, iy)
        if ix < Nx
            dh_dx = (h[ix+1, iy] - h[ix, iy]) * invdx

            v_nw = v[ix,   iy];  v_ne = v[ix+1, iy]
            v_sw = (iy == 1) ? v[ix,   iy] : v[ix,   iy-1]
            v_se = (iy == 1) ? v[ix+1, iy] : v[ix+1, iy-1]
            v_avg = 0.25 * (v_nw + v_ne + v_sw + v_se)

            # Total wind stress = background + ENSO anomaly
            du[ix, iy] = β * Y_h[ix, iy] * v_avg - g_p * dh_dx -
                         (r + Rs_h[ix, iy]) * u[ix, iy] -
                         wind_coeff * (U_a[ix, iy] + U_bg[ix, iy])
        else
            du[ix, iy] = 0.0
        end

        # dv at v-point (ix, iy+½)
        u_se = u[ix,   iy]
        u_sw = (ix == 1) ? 0.0 : u[ix-1, iy]

        if iy < Ny
            dh_dy = (h[ix, iy+1] - h[ix, iy]) * invdy
            u_ne  = u[ix,   iy+1]
            u_nw  = (ix == 1) ? 0.0 : u[ix-1, iy+1]
        else
            dh_dy = 0.0
            u_ne  = u_se
            u_nw  = u_sw
        end
        u_avg = 0.25 * (u_se + u_sw + u_ne + u_nw)

        dv[ix, iy] = -β * Y_v[ix, iy] * u_avg - g_p * dh_dy -
                     (r + Rs_v[ix, iy]) * v[ix, iy]
    end
    return
end

# ============================================================
# Tendency wrappers
# ============================================================
function atm_tendencies!(dU_a, dV_a, dφ_a, U_a, V_a, φ_a, h,
                         Y_h, Y_v, Rs_h, Rs_v,
                         β, ε_a, c_a_sq, α_atm, dx, dy, Nx, Ny)
    @parallel (1:Nx, 1:Ny) compute_atm_rhs!(
        dU_a, dV_a, dφ_a, U_a, V_a, φ_a, h,
        Y_h, Y_v, Rs_h, Rs_v, β, ε_a, c_a_sq, α_atm, dx, dy, Nx, Ny)
end

function ocean_tendencies!(du, dv, dh, u, v, h, U_a, U_bg,
                            Y_h, Y_v, Rs_h, Rs_v,
                            β, g_p, r, H, wind_coeff, dx, dy, Nx, Ny)
    @parallel (1:Nx, 1:Ny) compute_rhs!(
        du, dv, dh, u, v, h, U_a, U_bg, Y_h, Y_v, Rs_h, Rs_v,
        β, g_p, r, H, wind_coeff, dx, dy, Nx, Ny)
end

function all_tendencies!(du, dv, dh, dU_a, dV_a, dφ_a,
                          u,  v,  h,  U_a,  V_a,  φ_a,
                          U_bg,
                          Y_h, Y_v, Rs_h, Rs_v,
                          β, g_p, r, H, wind_coeff,
                          ε_a, c_a_sq, α_atm,
                          dx, dy, Nx, Ny)
    atm_tendencies!(dU_a, dV_a, dφ_a, U_a, V_a, φ_a, h,
                    Y_h, Y_v, Rs_h, Rs_v, β, ε_a, c_a_sq, α_atm, dx, dy, Nx, Ny)
    ocean_tendencies!(du, dv, dh, u, v, h, U_a, U_bg,
                      Y_h, Y_v, Rs_h, Rs_v, β, g_p, r, H, wind_coeff, dx, dy, Nx, Ny)
end

# ============================================================
# RK4 step — all 6 prognostic fields advanced simultaneously
# ============================================================
function rk4_step!(u, v, h, U_a, V_a, φ_a,
                   U_bg,
                   Y_h, Y_v, Rs_h, Rs_v,
                   β, g_p, r, H, wind_coeff,
                   ε_a, c_a_sq, α_atm,
                   dx, dy, dt, Nx, Ny,
                   k1u, k1v, k1h, k1U, k1V, k1φ,
                   k2u, k2v, k2h, k2U, k2V, k2φ,
                   k3u, k3v, k3h, k3U, k3V, k3φ,
                   k4u, k4v, k4h, k4U, k4V, k4φ,
                   tu,  tv,  th,  tU,  tV,  tφ)
    h2 = 0.5 * dt
    d6 = dt / 6.0

    # Stage 1
    all_tendencies!(k1u, k1v, k1h, k1U, k1V, k1φ,
                    u, v, h, U_a, V_a, φ_a, U_bg,
                    Y_h, Y_v, Rs_h, Rs_v,
                    β, g_p, r, H, wind_coeff, ε_a, c_a_sq, α_atm, dx, dy, Nx, Ny)

    tu .= u   .+ h2.*k1u;  tv .= v   .+ h2.*k1v;  th .= h   .+ h2.*k1h
    tU .= U_a .+ h2.*k1U;  tV .= V_a .+ h2.*k1V;  tφ .= φ_a .+ h2.*k1φ

    # Stage 2
    all_tendencies!(k2u, k2v, k2h, k2U, k2V, k2φ,
                    tu, tv, th, tU, tV, tφ, U_bg,
                    Y_h, Y_v, Rs_h, Rs_v,
                    β, g_p, r, H, wind_coeff, ε_a, c_a_sq, α_atm, dx, dy, Nx, Ny)

    tu .= u   .+ h2.*k2u;  tv .= v   .+ h2.*k2v;  th .= h   .+ h2.*k2h
    tU .= U_a .+ h2.*k2U;  tV .= V_a .+ h2.*k2V;  tφ .= φ_a .+ h2.*k2φ

    # Stage 3
    all_tendencies!(k3u, k3v, k3h, k3U, k3V, k3φ,
                    tu, tv, th, tU, tV, tφ, U_bg,
                    Y_h, Y_v, Rs_h, Rs_v,
                    β, g_p, r, H, wind_coeff, ε_a, c_a_sq, α_atm, dx, dy, Nx, Ny)

    tu .= u   .+ dt.*k3u;  tv .= v   .+ dt.*k3v;  th .= h   .+ dt.*k3h
    tU .= U_a .+ dt.*k3U;  tV .= V_a .+ dt.*k3V;  tφ .= φ_a .+ dt.*k3φ

    # Stage 4
    all_tendencies!(k4u, k4v, k4h, k4U, k4V, k4φ,
                    tu, tv, th, tU, tV, tφ, U_bg,
                    Y_h, Y_v, Rs_h, Rs_v,
                    β, g_p, r, H, wind_coeff, ε_a, c_a_sq, α_atm, dx, dy, Nx, Ny)

    u   .+= d6 .* (k1u .+ 2.0.*k2u .+ 2.0.*k3u .+ k4u)
    v   .+= d6 .* (k1v .+ 2.0.*k2v .+ 2.0.*k3v .+ k4v)
    h   .+= d6 .* (k1h .+ 2.0.*k2h .+ 2.0.*k3h .+ k4h)
    U_a .+= d6 .* (k1U .+ 2.0.*k2U .+ 2.0.*k3U .+ k4U)
    V_a .+= d6 .* (k1V .+ 2.0.*k2V .+ 2.0.*k3V .+ k4V)
    φ_a .+= d6 .* (k1φ .+ 2.0.*k2φ .+ 2.0.*k3φ .+ k4φ)
end


struct Coordinates
    _xs_km::Vector{Float64}
    _ys_km::Vector{Float64}
end

# ============================================================
# Main simulation
# ============================================================
function run_simulation(cfg::SimConfig)
    (; β, g_p, r_damp, H_mean,
       c_atm, ε_atm, α_atm, wind_coeff, U_trade,
       Lx, Ly, nx, ny, dt, nt, nout, h_amp,
       sponge_width_frac, sponge_rate_max,
       job_name) = cfg

    dx = Lx / nx
    dy = Ly / ny

    d_sponge = sponge_width_frac * Ly
    c_ocean  = sqrt(g_p * H_mean)
    c_a_sq   = c_atm^2

    # Bjerknes coupling parameter and mean thermocline tilt
    μ     = α_atm * wind_coeff / (ε_atm * r_damp)
    σ     = α_atm * wind_coeff / ε_atm - r_damp
    Δh_bg = wind_coeff * U_trade * Lx / g_p   # west-east tilt from background wind

    println("=== Ocean-Atmosphere Coupled Shallow Water Model (C-grid) ===")
    @printf "  Job            : %s\n"                        job_name
    @printf "  Domain         : %.0f km × %.0f km\n"         Lx/1e3 Ly/1e3
    @printf "  Grid           : %d × %d  (dx=%.1f km, dy=%.1f km)\n" nx ny dx/1e3 dy/1e3
    @printf "  β              : %.2e m⁻¹ s⁻¹\n"              β
    @printf "  g′=%.4f m s⁻², H=%.1f m,  c_ocean=%.2f m s⁻¹  CFL=%.3f\n" g_p H_mean c_ocean c_ocean*dt/dx
    @printf "  c_atm=%.1f m s⁻¹  CFL_x=%.3f  CFL_y=%.3f\n"  c_atm c_atm*dt/dx c_atm*dt/dy
    @printf "  Atm ε_a        : %.2e s⁻¹  (τ_fric=%.1f days)\n" ε_atm 1/(ε_atm*86400)
    @printf "  α_atm          : %.3e m s⁻³\n"                α_atm
    @printf "  wind_coeff     : %.3e s⁻¹\n"                  wind_coeff
    @printf "  Bjerknes μ     : %.3f   σ = %.2e s⁻¹\n"       μ σ
    @printf "  U_bg (Walker)  : %.1f m s⁻¹  →  Δh_bg = %.1f m (W deeper)\n" U_trade Δh_bg
    @printf "  dt=%.0f s,  total=%.1f days (%d steps)\n"     dt nt*dt/86400.0 nt
    println()

    c_atm  * dt / dx > 1.0 && @warn "Atmospheric CFL_x > 1 — may be unstable!"
    c_atm  * dt / dy > 1.0 && @warn "Atmospheric CFL_y > 1 — may be unstable!"
    c_ocean * dt / dx > 1.0 && @warn "Ocean CFL > 1 — may be unstable!"

    # ---- Grid coordinates ----
    xs_c = collect(LinRange(-Lx/2 + dx/2, Lx/2 - dx/2, nx))
    ys_c = collect(LinRange(-Ly/2 + dy/2, Ly/2 - dy/2, ny))
    ys_v = ys_c .+ dy/2

    Y_h_cpu = Float64[ys_c[j] for _ in 1:nx, j in 1:ny]
    Y_v_cpu = Float64[ys_v[j] for _ in 1:nx, j in 1:ny]

    # ---- Sponge layer: quadratic profile ----
    Ly_half = Ly / 2
    function sponge_at(y)
        if y < -Ly_half + d_sponge
            s = (-Ly_half + d_sponge - y) / d_sponge
            return sponge_rate_max * s * s
        elseif y > Ly_half - d_sponge
            s = (y - (Ly_half - d_sponge)) / d_sponge
            return sponge_rate_max * s * s
        else
            return 0.0
        end
    end

    Rs_h_cpu = Float64[sponge_at(ys_c[j]) for _ in 1:nx, j in 1:ny]
    Rs_v_cpu = Float64[sponge_at(ys_v[j]) for _ in 1:nx, j in 1:ny]

    # ---- Ocean IC: linear westward deepening × equatorial Gaussian ----
    L_d = sqrt(sqrt(g_p * H_mean) / β)
    h_cpu = Float64[
        -h_amp * xs_c[i] / (Lx/2) * exp(-ys_c[j]^2 / (4 * L_d^2))
        for i in 1:nx, j in 1:ny
    ]

    # ---- Background Walker wind profile (fixed, drives mean tilt) ----
    L_d_a    = sqrt(c_atm / β)
    U_bg_cpu = Float64[
        U_trade * exp(-ys_c[j]^2 / (2 * L_d_a^2))
        for _ in 1:nx, j in 1:ny
    ]

    @printf "  Ocean L_d      : %.0f km\n"  L_d / 1e3
    @printf "  Atm   L_d_a    : %.0f km\n"  L_d_a / 1e3
    println()

    # ---- Device arrays ----
    Y_h  = Data.Array(Y_h_cpu)
    Y_v  = Data.Array(Y_v_cpu)
    Rs_h = Data.Array(Rs_h_cpu)
    Rs_v = Data.Array(Rs_v_cpu)

    u    = @zeros(nx, ny)
    v    = @zeros(nx, ny)
    h    = Data.Array(h_cpu)

    U_bg = Data.Array(U_bg_cpu)   # fixed background wind → ocean only
    U_a  = @zeros(nx, ny)         # atmospheric anomaly: start at zero
    V_a  = @zeros(nx, ny)
    φ_a  = @zeros(nx, ny)

    # ---- RK4 stage arrays — ocean ----
    k1u = @zeros(nx, ny);  k1v = @zeros(nx, ny);  k1h = @zeros(nx, ny)
    k2u = @zeros(nx, ny);  k2v = @zeros(nx, ny);  k2h = @zeros(nx, ny)
    k3u = @zeros(nx, ny);  k3v = @zeros(nx, ny);  k3h = @zeros(nx, ny)
    k4u = @zeros(nx, ny);  k4v = @zeros(nx, ny);  k4h = @zeros(nx, ny)

    # ---- RK4 stage arrays — atmosphere ----
    k1U = @zeros(nx, ny);  k1V = @zeros(nx, ny);  k1φ = @zeros(nx, ny)
    k2U = @zeros(nx, ny);  k2V = @zeros(nx, ny);  k2φ = @zeros(nx, ny)
    k3U = @zeros(nx, ny);  k3V = @zeros(nx, ny);  k3φ = @zeros(nx, ny)
    k4U = @zeros(nx, ny);  k4V = @zeros(nx, ny);  k4φ = @zeros(nx, ny)

    # ---- RK4 temporary arrays ----
    tu = @zeros(nx, ny);  tv = @zeros(nx, ny);  th = @zeros(nx, ny)
    tU = @zeros(nx, ny);  tV = @zeros(nx, ny);  tφ = @zeros(nx, ny)

    nframes    = nt ÷ nout
    h_frames   = Vector{Matrix{Float64}}(undef, nframes)
    U_a_frames = Vector{Matrix{Float64}}(undef, nframes)

    println("Running simulation…")
    t_wall    = time()
    frame_idx = 0

    for it in 1:nt
        rk4_step!(u, v, h, U_a, V_a, φ_a,
                  U_bg,
                  Y_h, Y_v, Rs_h, Rs_v,
                  β, g_p, r_damp, H_mean, wind_coeff,
                  ε_atm, c_a_sq, α_atm,
                  dx, dy, dt, nx, ny,
                  k1u, k1v, k1h, k1U, k1V, k1φ,
                  k2u, k2v, k2h, k2U, k2V, k2φ,
                  k3u, k3v, k3h, k3U, k3V, k3φ,
                  k4u, k4v, k4h, k4U, k4V, k4φ,
                  tu, tv, th, tU, tV, tφ)

        # east-wall BC guard against floating-point drift
        u[end, :]   .= 0.0
        U_a[end, :] .= 0.0

        # Since north/south boundary is not fully-closed(instead dissipate energy using sponge, energy gradually accumulate, adjust manually)
        h .= clamp.(h, -20.0, 20.0)
        h .-= mean(h)

        if it % nout == 0
            frame_idx += 1
            snap   = Array(h)
            snap_U = Array(U_a)
            h_frames[frame_idx]   = snap
            U_a_frames[frame_idx] = snap_U
            @printf("step %5d / %d  (day %6.2f)  max|h| = %7.3f m  max|U_a| = %6.3f m/s\n",
                    it, nt, it*dt/86_400.0, maximum(abs, snap), maximum(abs, snap_U))
        end
    end

    @printf "\nDone in %.1f s.  Saving data…\n\n" (time() - t_wall)

    xs_km = xs_c ./ 1e3
    ys_km = ys_c ./ 1e3
    coord = Coordinates(xs_km, ys_km)

    jldsave(joinpath(cfg.output_dir, "h_frames.jld2");  h_frames, U_a_frames, U_bg=U_bg_cpu)
    jldsave(joinpath(cfg.output_dir, "simulation_coords.jld2"); coord)
end
